### PR TITLE
added linting/building/testing to github actions

### LINKED ISSUE #4: Add github actions
- compile
- lint
- run tests

### PR DESCRIPTION
**Pull request by MrDeadCe11**
closes #4

### CODE REVIEW

**Review by pi0neerpat — CHANGES_REQUESTED** [review]
Syntax error, see https://github.com/open-dollar/treasury-backed-cdp-savior/actions/runs/9119197311

**Comment by pi0neerpat** [comment]
Cool its working!

**Comment by MrDeadCe11** [comment]
> Cool its working!

**Comment by MrDeadCe11** [comment]
ok looks like we're ready with this one.

**Comment by MrDeadCe11** [comment]
@pi0neerpat if you can, add the ARB_MAINNET_RPC and ARB_MAINNET_DEPLOYER_PK .env variables for the e2e testing in the actions.

**Comment by pi0neerpat** [comment]
Ok added the RPC and PK. Now getting 
```
Suite result: ok. 6 passed; 0 failed; 0 skipped; finished in 6.23s (2.89ms CPU time)
2024-05-19T03:18:00.172038Z ERROR sharedbackend: Failed to send/recv `basic` err=failed to get account for 0x000000000000000000000000000000000000114f: Max retries exceeded address=0x000000000000000000000000000000000000114f
```

**Comment by pi0neerpat** [comment]
Remove e2e tests and trigger action

**Review by pi0neerpat — APPROVED** [review]

**Pull request merged**
